### ISSUE TITLE
SME Review - Workshop outline

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [solliancenet/MCW-Managed-open-source-databases-on-Azure#1]
Please place all feedback to the workshop outline in this issue by continuing the conversation below.

**Comment by steelecode01** [comment]
1. Scale
> Historical data is growing by over 2.9 GB 
> Queries that used to run in 3-5 seconds now take 30 minutes or longer to complete. 
Let's tweak these numbers to make more sense. Perhaps change "30 minutes or longer" to "several minutes"

2. Multi-tenancy
Wouldn't the biggest downsides of sharding be maintenance and increased complexity of aggregated views?

3. Process streaming...
I found this point generally confusing!

4+6. Flat file processing & Advanced Dashboards
Could combine with 6, as both are insight related. The HoL solution can still be 2-parts to show off the different capabilities. 

5. Resilient stream processing
Can we mention lack of skills and/or bandwidth? These complex scenarios can be solved without Azure, but the customer will end up doing more heavy lifting. We can highlight how Azure reduces the technical debt of the solution.

**Comment by joelhulen** [comment]
Thanks for the feedback, @steelecode01. I have made changes based on your feedback. Please take a look and let me know if there needs to be any additional clarification.

**Comment by DawnmarieDesJardins** [comment]
Closing outline issues.
